window.LIMA_PRODUCTS = [
  {
    id: "glasses-4-6x",
    name: "Glasses-Type Surgical Loupes",
    short: "Lightweight binocular loupes with six frame colours and 4X–6X magnification.",
    category: "loupes",
    badge: "Best for daily clinic",
    image: "images/products/glasses-type.jpg",
    gallery: ["images/products/glasses-type.jpg", "images/products/5x-angular.jpg"],
    priceLabel: "Price on request",
    delivery: "10–18 working days",
    preorder: true,
    colors: ["Green", "Black", "Silver", "Orange", "Grey", "White"],
    magnifications: ["4X", "5X", "6X"],
    specs: {
      Magnification: "4X / 5X / 6X",
      "Working distance": "350–450 mm",
      "Pupil distance": "52–76 mm",
      "Field of view": "50 mm",
      "Depth of field": "50 mm",
      Frame: "Lightweight alloy, six colour options",
      Compatibility: "Wear over myopia glasses; strap fixation",
    },
    packing: [
      "Straight-tube glasses loupes",
      "Fixed glasses rope",
      "Soft nose pad",
      "Cloth bag",
      "Protective case",
      "Instruction manual, cleaning cloth, screwdriver, spare screws",
    ],
    usedFor: [
      "General dentistry and restorative work",
      "Oral surgery and implant placement",
      "ENT and minor surgical procedures",
      "Any close-field work that needs a natural line of sight without stooping",
    ],
    why: "These Galilean-style glasses loupes sit on a lightweight frame so the clinician keeps a natural cervical angle. Magnification enlarges the operating field, reducing missed details in caries, margins, sutures, and canal orifices. Adjustable angle and pupil distance keep both eyes fused on one stereo image, which lowers eye strain during long sessions.",
    forWhom:
      "Dentists, oral surgeons, ENT clinicians, and theatre staff who want a daily-wear frame with interchangeable magnification rather than a through-the-lens custom pair.",
  },
  {
    id: "angular-5x",
    name: "5X Angular Surgical Loupes",
    short: "Angled 5X HD binocular system for implant, endodontics, and precision surgery.",
    category: "loupes",
    badge: "No stooping",
    image: "images/products/5x-angular.jpg",
    gallery: ["images/products/5x-angular.jpg", "images/products/5x-binocular.jpg"],
    priceLabel: "Price on request",
    delivery: "12–21 working days",
    preorder: true,
    colors: ["Six frame colours"],
    magnifications: ["5X"],
    specs: {
      Magnification: "5X HD",
      "Working distance": "450 mm",
      "Pupillary distance": "52–76 mm",
      "Field of view": "73 mm",
      Optics: "Imported glass lenses",
      Adjustments: "Rotary working distance, angle, left–right pupil distance",
      Posture: "Natural-angle observation — no bending, less cervical strain",
    },
    packing: [
      "5X angled binocular loupes",
      "Fixed glasses rope",
      "Cloth bag",
      "Protective case",
      "Instruction manual and small tools",
    ],
    usedFor: [
      "Dental implant and root-canal procedures",
      "Periodontal and restorative microsurgery",
      "Precision observation in confined oral or surgical fields",
    ],
    why: "Angular (deflected) optics let you look slightly downward through the barrels while the neck stays closer to neutral. 5X magnification is the typical step-up when 2.5X is no longer enough for canal location, implant osteotomy, or fine soft-tissue work. Rotary working-distance and PD sliders keep the image sharp as you move between sitting and standing.",
    forWhom:
      "Implantologists, endodontists, and surgeons who already know they need 5X and want an angled housing to protect the neck during long cases.",
  },
  {
    id: "binocular-5x",
    name: "5X Binocular Loupes (Angled)",
    short: "Special angled loupes for implant and root-canal work, with cervical-fatigue relief.",
    category: "loupes",
    badge: "Implant & RCT",
    image: "images/products/5x-binocular.jpg",
    gallery: [
      "images/products/5x-binocular.jpg",
      "images/products/angled-features.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "12–21 working days",
    preorder: true,
    colors: ["Black / orange frames as shown"],
    magnifications: ["5X"],
    specs: {
      Magnification: "5X",
      "Working distance": "450 mm",
      "Pupillary distance": "52–76 mm",
      "Field of view": "73 mm",
      Features: "High-definition imaging, independent left/right PD, ultra-light frame",
    },
    packing: [
      "Angled loupes",
      "Fixed glasses rope",
      "Cloth bag",
      "Hard case",
      "Instruction booklet",
    ],
    usedFor: [
      "Implant surgery",
      "Root-canal treatment",
      "Any procedure where the operator currently hunches over the patient",
    ],
    why: "When the barrels are mounted at an angle, the eyes look through the optics while the head remains more upright. That single geometry change is why angled loupes are specified for dentists who already have neck or shoulder fatigue from years of stooping. 5X keeps enamel–dentin junctions, file tips, and osteotomy walls clearly resolved.",
    forWhom:
      "Dentists converting from unaided vision or from 2.5X Galilean loupes, and surgical teams who want a dedicated angled 5X pair.",
  },
  {
    id: "angled-4-6x",
    name: "4–6X Angled Surgical Loupes",
    short: "Ergonomic 4X, 5X, or 6X angled loupes for stomatology, ENT, dental, and surgical work.",
    category: "loupes",
    badge: "Ergonomic series",
    image: "images/products/angled-4-6x.jpg",
    gallery: [
      "images/products/angled-4-6x.jpg",
      "images/products/angled-features.jpg",
      "images/products/premium-myopia.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "12–21 working days",
    preorder: true,
    colors: ["Premium grey", "White", "Orange", "Green", "Pink"],
    magnifications: ["4X", "5X", "6X"],
    specs: {
      Magnification: "4X / 5X / 6X (optional)",
      "Working distance": "350–450 mm",
      "Pupil distance": "52–76 mm",
      "Field of view": "50 mm",
      "Depth of field": "50 mm",
      Frame: "Upgraded ergonomic design, myopia / presbyopia compatible",
      Weight: "Lightweight for long cases",
    },
    packing: [
      "Angled surgical loupes (selected magnification)",
      "Head strap",
      "Soft nose pad",
      "Carry case",
    ],
    usedFor: [
      "Stomatology and dental surgery",
      "Otolaryngology (ENT)",
      "General and specialty surgical operations",
    ],
    why: "Higher magnification without an angled barrel often forces the operator to drop the chin. This series keeps 4X–6X power while the frame geometry reduces hunching and bowing. Independent pupil-distance and flip-up style barrels let you glance at the room without removing the glasses.",
    forWhom:
      "Clinicians who want one angled platform and will choose 4X for wider field, 5X as the all-rounder, or 6X for the finest dental and microsurgical detail.",
  },
  {
    id: "magnetic-4-6x",
    name: "Magnetic-Attached Surgical Loupes",
    short: "One frame, 4X / 5X / 6X magnetic barrels — change magnification between cases.",
    category: "loupes",
    badge: "Interchangeable lenses",
    image: "images/products/magnetic-loupes.jpg",
    gallery: [
      "images/products/magnetic-loupes.jpg",
      "images/products/magnetic-light.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "12–21 working days",
    preorder: true,
    colors: ["Grey", "White", "Blue", "Green", "Pink"],
    magnifications: ["4X", "5X", "6X"],
    specs: {
      Magnification: "4X / 5X / 6X interchangeable",
      "Working distance": "350–450 mm",
      "Pupil distance": "52–76 mm",
      "Field of view": "50 mm",
      "Depth of field": "50 mm",
      Mount: "Magnetic barrels + optional lenses",
      Compatibility: "Presbyopia-compatible; can be used with near-sighted glasses",
    },
    packing: [
      "Magnetic frame",
      "4X, 5X, and 6X barrel set (as ordered)",
      "Optional accessory lenses",
      "Carry case",
    ],
    usedFor: [
      "Clinics that share a pair across operators",
      "Mixed lists: exam at 4X, surgery at 5X–6X",
      "Users who already wear prescription glasses",
    ],
    why: "Magnetic barrels click on and off so one chassis covers several clinical needs. That matters in a dental or ENT department where morning hygiene, afternoon endo, and evening minor surgery do not all want the same power. Presbyopia-compatible geometry means near-work glasses can stay on.",
    forWhom:
      "Group practices, teaching clinics, and surgeons who refuse to own three separate frames for three magnifications.",
  },
  {
    id: "premium-25-35",
    name: "Premium 2.5X & 3.5X Surgical Loupes",
    short: "Entry-to-core clinical magnification with HD glass, five frame colours, 56 g class.",
    category: "loupes",
    badge: "Clinic standard",
    image: "images/products/premium-25-35.jpg",
    gallery: [
      "images/products/premium-25-35.jpg",
      "images/products/premium-myopia.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "10–18 working days",
    preorder: true,
    colors: ["Black", "Silver", "Brown", "Gunmetal"],
    magnifications: ["2.5X", "3.5X"],
    specs: {
      "2.5X working distance": "420–550 mm",
      "3.5X working distance": "420–550 mm",
      "Field of view": "120 mm",
      "Net weight": "56 g",
      Optics: "High-definition optical glass, low distortion",
      Frame: "Light, adjustable pupil distance, five colours",
    },
    packing: ["Loupes", "Eyeglass storage case", "Soft inserts"],
    usedFor: [
      "Dental restoration, hygiene, and diagnosis",
      "ENT and other surgical departments",
      "First pair of loupes for residents and new specialists",
    ],
    why: "2.5X is the classic first dental loupe: wide field, easy fusion, enough enlargement to see margins and caries without a steep learning curve. 3.5X tightens the view for finer restorative and surgical work while the 120 mm field still keeps orientation. At about 56 g the frame is intended for all-day wear.",
    forWhom:
      "General dentists, hygienists working under magnification, ENT, and surgeons who want a light Galilean pair before moving to 5X prism or angled systems.",
  },
  {
    id: "embedded-ttl",
    name: "Embedded (TTL) Surgical Loupes",
    short: "Through-the-lens titanium pair with customised pupil distance, 2.5X or 3.5X.",
    category: "loupes",
    badge: "Custom PD",
    image: "images/products/embedded-loupe.jpg",
    gallery: [
      "images/products/embedded-loupe.jpg",
      "images/products/embedded-clip-led.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "18–28 working days (custom PD)",
    preorder: true,
    colors: ["Black titanium frame"],
    magnifications: ["2.5X", "3.5X"],
    specs: {
      Type: "Embedded / through-the-lens (TTL)",
      Material: "Titanium alloy",
      Magnification: "2.5X or 3.5X",
      "Pupil distance": "Customised to the wearer",
      Optics: "High-definition optical lenses",
      Departments: "Dentistry, dental clinics, ENT, surgical departments",
    },
    packing: ["TTL loupes", "Protective case", "Care kit"],
    usedFor: [
      "Full-day dental practice",
      "Operators who want optics aligned exactly to their PD",
      "Clinicians who prefer barrels set into the carrier lens rather than flip-up",
    ],
    why: "TTL (through-the-lens) loupes are drilled into the carrier lenses at your measured interpupillary distance. The optical axes sit where your eyes actually rest, so you get a larger usable field and less peripheral ‘swim’ than a generic flip-up. Titanium keeps the chassis light for eight-hour lists.",
    forWhom:
      "Dentists and surgeons ready to commit to a personalised pair. Pre-order includes your PD measurement via WhatsApp.",
  },
  {
    id: "led-3w",
    name: "LED Light Source Attachment (3W)",
    short: "30 000 lux coaxial LED for surgical loupes, with four-colour battery pack.",
    category: "lighting",
    badge: "Loupe light",
    image: "images/products/5x-angular.jpg",
    gallery: [
      "images/products/magnetic-light.jpg",
      "images/products/5x-angular.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "10–18 working days",
    preorder: true,
    colors: ["Red", "Silver", "Blue", "Black battery packs"],
    magnifications: [],
    specs: {
      "LED power": "3W",
      Brightness: "30 000 lux",
      "Battery life": "Confirmed on order (pack dependent)",
      "Service life": "10 000 hours",
      "Input voltage": "AC 100–240 V / 50–60 Hz",
      Mount: "Available for surgical loupes in this catalogue",
    },
    packing: ["LED lamp head and cable", "Battery pack (colour of choice)", "Charger"],
    usedFor: [
      "Oral cavity illumination without moving the overhead light",
      "Shadow-free work in ENT and minor surgery",
      "Pairing with any Lima loupe in this catalogue",
    ],
    why: "Magnification without a coaxial light still leaves the field in the shadow of your own head. A 3W, 30 000 lux loupe-mounted LED travels with your line of sight, so implant osteotomies, canal orifices, and deep surgical pockets stay evenly lit. The belt or pocket battery pack is offered in four colours to match clinic kits.",
    forWhom:
      "Any loupe user working in the mouth, ear, or a deep cavity. Order with a loupe as a set or as an add-on.",
  },
  {
    id: "clip-led-5w",
    name: "Clip-On LED Headlight (5W)",
    short: "5W clip lamp, ≥4 h continuous work, 15 000–30 000 lux, four frame colours.",
    category: "lighting",
    badge: "5W clip lamp",
    image: "images/products/premium-25-35.jpg",
    gallery: [
      "images/products/premium-25-35.jpg",
      "images/products/embedded-clip-led.jpg",
    ],
    priceLabel: "Price on request",
    delivery: "10–18 working days",
    preorder: true,
    colors: ["Black", "Silver", "Brown", "Gunmetal"],
    magnifications: [],
    specs: {
      "LED power": "5W",
      "Continuous working time": "≥ 4 hours",
      "Light intensity": "15 000–30 000 lux",
      "Service life": "10 000 hours",
      "Input voltage": "AC 100–240 V / 50–60 Hz",
    },
    packing: ["Clip-on LED unit", "Battery / control pack", "Charger"],
    usedFor: [
      "Clipping onto loupes or spectacle frames",
      "Dental and surgical fields when a 3W lamp is not enough",
      "Backup illumination for outreach or satellite clinics",
    ],
    why: "The 5W clip lamp is the higher-output option in this catalogue. Four-plus hours of continuous run time covers a typical morning list. Intensity in the 15 000–30 000 lux band is what most dental and minor-surgery operators expect from a modern portable headlight.",
    forWhom:
      "Dentists and surgeons who already own frames and need a clip light, or who want a spare 5W unit beside the 3W loupe light.",
  },
  {
    id: "storage-case",
    name: "Eyeglass Storage Case",
    short: "Fitted hard case with foam insert for premium 2.5X / 3.5X loupes.",
    category: "accessories",
    badge: "Accessory",
    image: "images/products/premium-25-35.jpg",
    gallery: ["images/products/premium-25-35.jpg"],
    priceLabel: "Price on request",
    delivery: "7–14 working days",
    preorder: true,
    colors: ["Black"],
    magnifications: [],
    specs: {
      Type: "Hard eyeglass / loupe case",
      Interior: "Custom foam cut-out",
      Use: "Protects barrels and frame in transit between clinic and theatre",
    },
    packing: ["Storage case with foam"],
    usedFor: [
      "Protecting loupes between surgeries",
      "Replacement case if the original insert is worn",
    ],
    why: "Loupe barrels knock out of collimation if they ride loose in a bag. The fitted foam case is the same style shown with the premium 2.5X / 3.5X set and is sold separately for extra stations or replacements.",
    forWhom: "Existing Lima loupe owners and anyone ordering a second clinic kit.",
  },
];
